### ISSUE TITLE
Misses obvious differences. 

### ISSUE THREAD

**Issue by tony-gutierrez** [justspamjustin/online-json-diff#14]
Does not notify about missing attributes between the two objects.

**Comment by justspamjustin** [comment]
Can you provide an example where this is happening? Missing properties are supposed to be highlighted as in the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/1090945/15844685/7bd4617a-2c29-11e6-93b7-f0ca751fc817.png)

**Comment by tony-gutierrez** [comment]
I can try to recreate. As far as I can tell, it just stops processing at a
certain point. You should probably not have it online without a disclaimer.
It led to a lot of wasted time.

**Comment by fgrosse** [comment]
I doubt a disclaimer would have prevented the issue. Maybe you can supply some actual input data that can be used to recreate the bug you are describing? If that is not possible maybe you can describe what kind of data you were using (deeply nested [how deep?], very large values, number of keys, etc...) Just complaining that the tool wasted a lot of time is not constructive.

Anyway so far this is working nicely for me and I didnt experience any issues. Wanted to take the oportunity to thank you for your work @justspamjustin :)

**Comment by justspamjustin** [comment]
please reopen reproducible steps. Thanks.
