### ISSUE TITLE
Can we generate a diff file?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [justspamjustin/online-json-diff#17]
Great work here!

Please can we generate a diff file? 

It would be useful if we could get a valid JSON result that has just the change set

Again, great work.

Thanks

**Comment by justspamjustin** [comment]
@CharlesOkwuagwu are you suggesting the ability to download a diff file? Do you have any suggestions for what format it should be in? (thanks for the feedback).

**Comment by CharlesOkwuagwu** [comment]
It should be a simple Json file.

**Comment by odeami** [comment]
https://github.com/flitbit/diff 
Differences

Differences are reported as one or more change records. Change records have the following structure:

kind - indicates the kind of change; will be one of the following:
N - indicates a newly added property/element
D - indicates a property/element was deleted
E - indicates a property/element was edited
A - indicates a change occurred within an array
path - the property path (from the left-hand-side root)
lhs - the value on the left-hand-side of the comparison (undefined if kind === 'N')
rhs - the value on the right-hand-side of the comparison (undefined if kind === 'D')
index - when kind === 'A', indicates the array index where the change occurred
item - when kind === 'A', contains a nested change record indicating the change that occurred at the array index

**Comment by justspamjustin** [comment]
I've added a download button to the cog menu (4129092133df07c3e3b0029f49f15979561f4705). It follows the JSON patch syntax: https://tools.ietf.org/html/rfc6902.
