### ISSUE TITLE
There is no validation for duplicate lines

### ISSUE THREAD

**Issue by clicman** [justspamjustin/online-json-diff#21]
Hi!
It is not mars json as invalid if duplicate field in it:

```
{
  "id":1,
  "required": false,
  "required": true
}
```

But should mak this json as invalid

**Comment by justspamjustin** [comment]
something interesting: jsonlint.com says the above json is valid.

**Comment by justspamjustin** [comment]
because I don't think that is actually technically invalid JSON and it doesn't hinder your progress in getting a diff of two objects, I'm closing this. Thanks!
